
# A string used as a project reference
project_id = "nbmomsntbamfthxfdnme"

[api]
# Port number for the API gateway
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage"]
# Extra schemas to add to the search_path of every request
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a view, table, or stored procedure. Limits payload size for accidental or malicious requests.
max_rows = 1000

[db]
# Port number for the database
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the admin interface.
[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
# List of redirect URLs for auth providers
additional_redirect_urls = ["https://localhost:3000"]
# Extended JWT expiry: 24 hours (86400 seconds) for better UX
jwt_expiry = 86400
# Refresh token expiry: 7 days (604800 seconds)
refresh_token_rotation_enabled = true
# Allow/disallow new user signups to your project.
enable_signup = true
# Security settings
password_min_length = 8
enable_anonymous_sign_ins = false

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, users need to confirm their email address before signing in.
double_confirm_changes = false
enable_confirmations = true

# Configure one of the supported auth providers
# [auth.external.apple]
# enabled = true
# client_id = ""
# secret = ""

[functions]
# Note that this function has access to all supabase features as it's executed by the server
[functions.mcp-handler]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.generate-embedding]
verify_jwt = true
